version: "3.9"
services:
  redis:
    container_name: redis
    hostname: redis
    image: myDockerImage:0.1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 5
    restart: unless-stopped
    stdin_open: true
    network_mode: bridge    # prevent creating new network

  web_py:
    container_name: web_py
    hostname: web_py
    # Create (build) image from base python:3.7-alpine with requirements.txt
    image: python-3.7-alpine-custom-flack:0.1        
    build:
      context: ./build
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    stdin_open: true
    network_mode: bridge    # prevent creating new network
    links:
      -  "redis"

